# The URL the site will be built for
base_url = "https://a.nvlkv.xyz"

title = "Aleksandr Novolokov"
description= "User experience engineer, full stack developer, artist."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

smart_punctuation = true

taxonomies = [
    { name = "period", feed = false, render = true },
    { name = "expertise", feed = false, render = true },
    { name = "stack", feed = false, render = true },
]

theme = "polymathic"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Put all your custom variables here
[extra]
[extra.poly]
menu_order = [
  "portfolio/_index.md",
  "resume/_index.md",
  "contact.md"
]
social_outlink=[
  {href="https://www.linkedin.com/in/anvlkv", title="LinkedIn"},
  {href="https://github.com/anvlkv", title="GitHub"},
  {href="https://exercism.org/profiles/anvlkv", title="Exercism"},
  {href="https://stackoverflow.com/users/1774187/anvlkv", title="StackOverflow"},
]
license="license.md"