accelerate launch  train.py \
  --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4" \
  --tokenizer_name="openai/clip-vit-large-patch14" \
  --dataset_name="./datasets/portfolio" \
  --resolution=512 --center_crop \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --gradient_checkpointing \
  --max_train_steps=15000 \
  --learning_rate=1e-05 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --output_dir="portfolio-model"