name: Deploy

# Deploy only when a change is pushed or merged to `main`
on: workflow_dispatch

jobs:
  spin:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.66
          targets: wasm32-wasi

      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1

      - name: Build and deploy
        uses: fermyon/actions/spin/deploy@v1
        with:
          fermyon_token: ${{ secrets.FERMYON_CLOUD_TOKEN }}
          variables: |
            db_branch=${{ secrets.XATA_BRANCH }}
            xata_key=${{ secrets.XATA_KEY }}
            xata_region=${{ secrets.XATA_REGION }}
            db_name=${{ secrets.XATA_DB_NAME }}
            xata_workspace=${{ secrets.XATA_WORKSPACE }}
